class ReminderMixin:
    # async def get_timers(self):
    #     ...

    async def dispatch_timers(self):
        ...

    async def wait_for_timers(self):
        ...

    async def call_timer(self):
        ...

    async def handle_timers(self):
        ...

    # async def create_timers(self):
    #     ...

    async def on_timer_complete(self):
        ...
    # lets work here what do here so, if i need the attributes O
